#!/bin/zsh
# if [[ ! -n "$ZSHRUN" ]]; then
#     source $HOME/dotfiles/zsh/zsh_prompt
# fi

source $ZSH/oh-my-zsh.sh

local -a precmd_functions
precmd_functions=( precmd_prompt )

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
zplug "zsh-users/zsh-syntax-highlighting"
zplug "lib/completion", from:oh-my-zsh

# antigen bundle cd
ZSH_THEME="powerlevel9k/powerlevel9k"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

autoload -U colors && colors
autoload -U compinit
compinit -C

plugins=(git)

POWERLEVEL9K_MODE='compatible'

# Disable dir/git icons
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''

DISABLE_AUTO_TITLE="true"

POWERLEVEL9K_VCS_STAGED_ICON='+'

POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='›'

POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
POWERLEVEL9K_VCS_UNSTAGED_ICON='●'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='i'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='o'
POWERLEVEL9K_VCS_STASH_ICON=''
POWERLEVEL9K_VCS_TAG_ICON=''
POWERLEVEL9K_VCS_BOOKMARK_ICON=''
POWERLEVEL9K_VCS_COMMIT_ICON='*'
POWERLEVEL9K_VCS_BRANCH_ICON='@'
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON='@!'
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_HG_ICON=''

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_SHORTEN_DELIMITER=""

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time virtualenv dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

POWERLEVEL9K_TIME_FOREGROUND='white'
POWERLEVEL9K_TIME_BACKGROUND='transparent'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='yellow'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='transparent'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='transparent'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='transparent'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='blue'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='transparent'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='blue'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='transparent'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="›"
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="↳  "
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="$ "

POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_STATUS_VERBOSE=false
export DEFAULT_USER="$USER"


export LSCOLORS=gxfxcxdxbxegedabagacad

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "$LS_COLORS"
zstyle -e ':completion:*:(ssh|scp|sshfs|ping|telnet|nc|rsync):*' hosts '
    reply=( ${=${${(M)${(f)"$(<~/.ssh/config)"}:#Host*}#Host }:#*\**} )'

setopt  auto_cd
setopt  auto_pushd
setopt  clobber
setopt  complete_aliases
setopt  extended_glob
setopt  hist_ignore_all_dups
setopt  hist_ignore_space
setopt  share_history
setopt  noflowcontrol
setopt  list_types
setopt  mark_dirs
setopt  path_dirs
setopt  prompt_percent
setopt  prompt_subst

HISTFILE=$HOME/.zsh_history
HISTFILESIZE=6553600
HISTSIZE=409600
SAVEHIST=409600
REPORTTIME=60

export LANG=sv_SE.UTF-8
export LC_ALL=$LANG
export LC_COLLATE=C

export GREP_OPTIONS='--color=auto'

PATH="/usr/local/bin:$PATH"

export GIT_EDITOR='nvim'
export LESS='-imJMWR'
export PAGER="less $LESS"
export MANPAGER=$PAGER
export GIT_PAGER=$PAGER
export BROWSER='chromium-browser'

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/VirtualDevEnvs

include () {
    [[ -s "$1" ]] && source "$1"
}

include ~/.nvm/nvm.sh

sfp() { ag --python "$*" --nocolor; }

wttr() {
  place=$1
  url='http://wttr.in/'$place
  curl $url
}
eval $(thefuck --alias)

export EDITOR="nvim"

alias dcp='docker-compose'
alias dcpe='dcp exec'

alias nvimrc='nvim ~/.config/nvim/init.vim'
alias vimrc='nvim ~/.vimrc'
alias zshrc='nvim ~/.zshrc'
alias nombom='npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install'
alias nvim='echo -ne "\033]0;nvim\007" && /usr/local/bin/nvim'
alias nviml='nvim --cmd "let light=1"'
alias vim='nvim'
alias expenv='export $(cat .env | xargs)'
alias urar='unrar x `find . -type f -name "*.rar" | grep -v "sub"`'

bindkey '^R' history-incremental-search-backward
clear
export PATH="/usr/local/opt/curl/bin:$PATH"
